"""advanced features

Revision ID: 283cf42a740b
Revises: 26c453b9af60
Create Date: 2026-05-06 16:48:27.532760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '283cf42a740b'
down_revision: Union[str, None] = '26c453b9af60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('habits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('icon', sa.String(length=40), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('target_per_week', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_habits_user_id'), 'habits', ['user_id'], unique=False)
    op.create_table('reflections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('sleep_hours', sa.Float(), nullable=True),
    sa.Column('mood', sa.Integer(), nullable=True),
    sa.Column('energy', sa.Integer(), nullable=True),
    sa.Column('shipped', sa.Text(), nullable=False),
    sa.Column('blocked', sa.Text(), nullable=False),
    sa.Column('tomorrow', sa.Text(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_reflection_user_date')
    )
    op.create_index(op.f('ix_reflections_date'), 'reflections', ['date'], unique=False)
    op.create_index(op.f('ix_reflections_user_id'), 'reflections', ['user_id'], unique=False)
    op.create_table('user_badges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('badge_code', sa.String(length=50), nullable=False),
    sa.Column('earned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'badge_code', name='uq_user_badge')
    )
    op.create_index(op.f('ix_user_badges_badge_code'), 'user_badges', ['badge_code'], unique=False)
    op.create_index(op.f('ix_user_badges_user_id'), 'user_badges', ['user_id'], unique=False)
    op.create_table('habit_checks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('habit_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['habit_id'], ['habits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('habit_id', 'date', name='uq_habit_date')
    )
    op.create_index(op.f('ix_habit_checks_date'), 'habit_checks', ['date'], unique=False)
    op.create_index(op.f('ix_habit_checks_habit_id'), 'habit_checks', ['habit_id'], unique=False)
    op.create_table('submission_reactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('emoji', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['task_submissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('submission_id', 'user_id', 'emoji', name='uq_reaction')
    )
    op.create_index(op.f('ix_submission_reactions_submission_id'), 'submission_reactions', ['submission_id'], unique=False)
    op.add_column('task_submissions', sa.Column('proof_hash', sa.String(length=64), nullable=True))
    op.add_column('task_submissions', sa.Column('is_duplicate_proof', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('task_submissions', sa.Column('ai_verified', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('task_submissions', sa.Column('ai_confidence', sa.Integer(), nullable=True))
    op.add_column('task_submissions', sa.Column('ai_reasoning', sa.Text(), nullable=False, server_default=''))
    op.create_index(op.f('ix_task_submissions_proof_hash'), 'task_submissions', ['proof_hash'], unique=False)
    op.add_column('users', sa.Column('level', sa.Integer(), nullable=False, server_default='1'))
    op.add_column('users', sa.Column('freeze_tokens', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('users', sa.Column('bio', sa.String(length=280), nullable=False, server_default=''))
    op.add_column('users', sa.Column('theme', sa.String(length=40), nullable=False, server_default='violet'))
    op.add_column('users', sa.Column('unlocked_themes', sa.String(length=400), nullable=False, server_default='violet'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'unlocked_themes')
    op.drop_column('users', 'theme')
    op.drop_column('users', 'bio')
    op.drop_column('users', 'freeze_tokens')
    op.drop_column('users', 'level')
    op.drop_index(op.f('ix_task_submissions_proof_hash'), table_name='task_submissions')
    op.drop_column('task_submissions', 'ai_reasoning')
    op.drop_column('task_submissions', 'ai_confidence')
    op.drop_column('task_submissions', 'ai_verified')
    op.drop_column('task_submissions', 'is_duplicate_proof')
    op.drop_column('task_submissions', 'proof_hash')
    op.drop_index(op.f('ix_submission_reactions_submission_id'), table_name='submission_reactions')
    op.drop_table('submission_reactions')
    op.drop_index(op.f('ix_habit_checks_habit_id'), table_name='habit_checks')
    op.drop_index(op.f('ix_habit_checks_date'), table_name='habit_checks')
    op.drop_table('habit_checks')
    op.drop_index(op.f('ix_user_badges_user_id'), table_name='user_badges')
    op.drop_index(op.f('ix_user_badges_badge_code'), table_name='user_badges')
    op.drop_table('user_badges')
    op.drop_index(op.f('ix_reflections_user_id'), table_name='reflections')
    op.drop_index(op.f('ix_reflections_date'), table_name='reflections')
    op.drop_table('reflections')
    op.drop_index(op.f('ix_habits_user_id'), table_name='habits')
    op.drop_table('habits')
    # ### end Alembic commands ###
