"""squads buddy

Revision ID: 2a97af7fb1ad
Revises: 283cf42a740b
Create Date: 2026-05-06 17:30:39.129489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2a97af7fb1ad'
down_revision: Union[str, None] = '283cf42a740b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('squads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('emoji', sa.String(length=8), nullable=False),
    sa.Column('group_streak_mode', sa.Boolean(), nullable=False),
    sa.Column('streak', sa.Integer(), nullable=False),
    sa.Column('longest_streak', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('buddy_pairs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_a', sa.UUID(), nullable=False),
    sa.Column('user_b', sa.UUID(), nullable=False),
    sa.Column('requested_by', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', 'ENDED', name='buddy_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('user_a <> user_b', name='ck_buddy_distinct'),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_a'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_b'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_a', 'user_b', name='uq_buddy_pair')
    )
    op.create_index(op.f('ix_buddy_pairs_status'), 'buddy_pairs', ['status'], unique=False)
    op.create_index(op.f('ix_buddy_pairs_user_a'), 'buddy_pairs', ['user_a'], unique=False)
    op.create_index(op.f('ix_buddy_pairs_user_b'), 'buddy_pairs', ['user_b'], unique=False)
    op.create_table('squad_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('squad_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['squad_id'], ['squads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('squad_id', 'user_id', name='uq_squad_member')
    )
    op.create_index(op.f('ix_squad_members_squad_id'), 'squad_members', ['squad_id'], unique=False)
    op.create_index(op.f('ix_squad_members_user_id'), 'squad_members', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_squad_members_user_id'), table_name='squad_members')
    op.drop_index(op.f('ix_squad_members_squad_id'), table_name='squad_members')
    op.drop_table('squad_members')
    op.drop_index(op.f('ix_buddy_pairs_user_b'), table_name='buddy_pairs')
    op.drop_index(op.f('ix_buddy_pairs_user_a'), table_name='buddy_pairs')
    op.drop_index(op.f('ix_buddy_pairs_status'), table_name='buddy_pairs')
    op.drop_table('buddy_pairs')
    op.drop_table('squads')
    # ### end Alembic commands ###
