"""organizations

Revision ID: e1ef0cb4466c
Revises: 2a97af7fb1ad
Create Date: 2026-05-06 18:51:59.181790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e1ef0cb4466c'
down_revision: Union[str, None] = '2a97af7fb1ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('invite_code', sa.String(length=20), nullable=False),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_invite_code'), 'organizations', ['invite_code'], unique=True)
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.add_column('daily_tasks', sa.Column('org_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_daily_tasks_org_id'), 'daily_tasks', ['org_id'], unique=False)
    op.create_foreign_key(None, 'daily_tasks', 'organizations', ['org_id'], ['id'], ondelete='CASCADE')
    op.add_column('squads', sa.Column('org_id', sa.UUID(), nullable=True))
    op.drop_constraint('squads_name_key', 'squads', type_='unique')
    op.create_index(op.f('ix_squads_org_id'), 'squads', ['org_id'], unique=False)
    op.create_unique_constraint('uq_squad_org_name', 'squads', ['org_id', 'name'])
    op.create_foreign_key(None, 'squads', 'organizations', ['org_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('org_id', sa.UUID(), nullable=True))
    org_role_enum = sa.Enum('OWNER', 'MODERATOR', 'MEMBER', name='org_role')
    org_role_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('users', sa.Column('org_role', org_role_enum, nullable=True))
    op.create_index(op.f('ix_users_org_id'), 'users', ['org_id'], unique=False)
    op.create_foreign_key(None, 'users', 'organizations', ['org_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###

    # --- Backfill: migrate any existing users/tasks/squads into a default org ---
    # Strategy: pick the first ADMIN user as owner; create a "Default Workspace"
    # organization; assign every existing user/task/squad to it. New deploys
    # without any users skip this entirely.
    op.execute("""
    DO $$
    DECLARE
        v_admin_id UUID;
        v_org_id UUID;
        v_invite TEXT;
    BEGIN
        -- Skip if there are no users yet
        IF NOT EXISTS (SELECT 1 FROM users) THEN
            RETURN;
        END IF;

        -- Pick first admin; fall back to first user
        SELECT id INTO v_admin_id FROM users WHERE role = 'ADMIN' ORDER BY created_at ASC LIMIT 1;
        IF v_admin_id IS NULL THEN
            SELECT id INTO v_admin_id FROM users ORDER BY created_at ASC LIMIT 1;
        END IF;

        v_invite := upper(substr(md5(random()::text), 1, 3) || '-' || substr(md5(random()::text), 1, 3) || '-' || substr(md5(random()::text), 1, 3));
        v_org_id := gen_random_uuid();

        INSERT INTO organizations (id, name, slug, description, invite_code, is_open, owner_id, created_at, updated_at)
        VALUES (v_org_id, 'Default Workspace', 'default', 'Auto-created workspace for existing users', v_invite, true, v_admin_id, now(), now());

        -- Assign all existing users
        UPDATE users
        SET org_id = v_org_id,
            org_role = (CASE
                WHEN id = v_admin_id THEN 'OWNER'
                WHEN role = 'MODERATOR' THEN 'MODERATOR'
                ELSE 'MEMBER'
            END)::org_role;

        -- Assign all existing tasks + squads
        UPDATE daily_tasks SET org_id = v_org_id WHERE org_id IS NULL;
        UPDATE squads SET org_id = v_org_id WHERE org_id IS NULL;
    END $$;
    """)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_org_id'), table_name='users')
    op.drop_column('users', 'org_role')
    op.drop_column('users', 'org_id')
    op.drop_constraint(None, 'squads', type_='foreignkey')
    op.drop_constraint('uq_squad_org_name', 'squads', type_='unique')
    op.drop_index(op.f('ix_squads_org_id'), table_name='squads')
    op.create_unique_constraint('squads_name_key', 'squads', ['name'])
    op.drop_column('squads', 'org_id')
    op.drop_constraint(None, 'daily_tasks', type_='foreignkey')
    op.drop_index(op.f('ix_daily_tasks_org_id'), table_name='daily_tasks')
    op.drop_column('daily_tasks', 'org_id')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_invite_code'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
