import { useEffect, useState } from 'react';
import { motion } from 'framer-motion';
import { Sparkles, Check, RefreshCw } from 'lucide-react';
import toast from 'react-hot-toast';
import { api } from '@/lib/api';
import { Card } from '@/components/ui/Card';
import { Button } from '@/components/ui/Button';
import { Badge } from '@/components/ui/Badge';

interface GeneratedTask {
  title: string;
  description: string;
  difficulty: string;
  points: number;
  is_required: boolean;
  proof_required: boolean;
  proof_instructions: string;
  task_date: string;
  deadline: string;
}

interface Profile {
  code: string;
  label: string;
  task_count: number;
}

export default function AITaskGen() {
  const [profiles, setProfiles] = useState<Profile[]>([]);
  const [profile, setProfile] = useState('general');
  const [count, setCount] = useState(5);
  const [tasks, setTasks] = useState<GeneratedTask[]>([]);
  const [generating, setGenerating] = useState(false);
  const [publishing, setPublishing] = useState<number | null>(null);
  const [bulkPublishing, setBulkPublishing] = useState(false);
  const [selected, setSelected] = useState<Set<number>>(new Set());

  useEffect(() => {
    api.get<Profile[]>('/ai/admin/profiles').then((r) => setProfiles(r.data));
  }, []);

  const [source, setSource] = useState<'groq' | 'local' | null>(null);

  async function generate() {
    setGenerating(true);
    try {
      const r = await api.post<{ tasks: GeneratedTask[]; source: 'groq' | 'local' }>(
        '/ai/admin/generate-tasks',
        { profile, count, use_ai: true },
      );
      setTasks(r.data.tasks);
      setSource(r.data.source);
      setSelected(new Set(r.data.tasks.map((_, i) => i)));
    } finally {
      setGenerating(false);
    }
  }

  async function publishOne(idx: number) {
    setPublishing(idx);
    try {
      await api.post('/tasks/', tasks[idx]);
      toast.success('Published');
      const next = new Set(selected);
      next.delete(idx);
      setSelected(next);
    } finally {
      setPublishing(null);
    }
  }

  async function publishSelected() {
    setBulkPublishing(true);
    try {
      const indices = Array.from(selected);
      for (const idx of indices) {
        await api.post('/tasks/', tasks[idx]);
      }
      toast.success(`Published ${indices.length} task${indices.length > 1 ? 's' : ''}`);
      setSelected(new Set());
    } finally {
      setBulkPublishing(false);
    }
  }

  function toggle(idx: number) {
    const next = new Set(selected);
    if (next.has(idx)) next.delete(idx);
    else next.add(idx);
    setSelected(next);
  }

  return (
    <div className="space-y-6">
      <motion.div initial={{ opacity: 0, y: -8 }} animate={{ opacity: 1, y: 0 }}>
        <h1 className="text-3xl font-display font-bold flex items-center gap-3">
          <Sparkles className="w-7 h-7 text-neon-cyan" /> AI Task Generator
        </h1>
        <p className="text-white/60 mt-1">
          Pick a profile, generate a pack, review, publish to all users.
        </p>
      </motion.div>

      <Card>
        <div className="flex gap-3 items-end flex-wrap">
          <div className="flex-1 min-w-[200px]">
            <label className="label">Profile</label>
            <select
              className="input"
              value={profile}
              onChange={(e) => setProfile(e.target.value)}
            >
              {profiles.map((p) => (
                <option key={p.code} value={p.code}>
                  {p.label}
                </option>
              ))}
            </select>
          </div>
          <div>
            <label className="label">Count</label>
            <input
              type="number"
              min={1}
              max={10}
              className="input w-24"
              value={count}
              onChange={(e) => setCount(Number(e.target.value))}
            />
          </div>
          <Button onClick={generate} loading={generating}>
            <Sparkles className="w-4 h-4" /> Generate
          </Button>
          {tasks.length > 0 && (
            <>
              <Button variant="ghost" onClick={generate}>
                <RefreshCw className="w-4 h-4" /> Reroll
              </Button>
              <Button
                onClick={publishSelected}
                loading={bulkPublishing}
                disabled={selected.size === 0}
              >
                <Check className="w-4 h-4" /> Publish selected ({selected.size})
              </Button>
            </>
          )}
        </div>
        {source && (
          <div className="mt-3 text-xs text-white/50">
            Generated by{' '}
            {source === 'groq' ? (
              <span className="text-neon-cyan">Groq AI</span>
            ) : (
              <span>local templates</span>
            )}
            {source === 'local' && (
              <span className="ml-2">
                — add <code className="px-1 bg-white/10 rounded">GROQ_API_KEY</code> to your .env
                for AI-generated tasks
              </span>
            )}
          </div>
        )}
      </Card>

      {tasks.length > 0 && (
        <div className="space-y-3">
          {tasks.map((t, idx) => (
            <Card key={idx} className="p-4">
              <div className="flex items-start gap-3">
                <input
                  type="checkbox"
                  className="mt-1.5 w-4 h-4 accent-neon-violet"
                  checked={selected.has(idx)}
                  onChange={() => toggle(idx)}
                />
                <div className="flex-1 min-w-0">
                  <div className="flex items-center gap-2 mb-1 flex-wrap">
                    <Badge tone={t.difficulty === 'hard' ? 'amber' : t.difficulty === 'insane' ? 'red' : 'cyan'}>
                      {t.difficulty}
                    </Badge>
                    {t.is_required && <Badge tone="violet">required</Badge>}
                    <span className="text-xs text-white/50">+{t.points} XP</span>
                  </div>
                  <div className="font-display font-semibold">{t.title}</div>
                  <p className="text-sm text-white/60 mt-0.5">{t.description}</p>
                  <p className="text-xs text-white/40 mt-1">
                    Proof: {t.proof_instructions}
                  </p>
                </div>
                <Button
                  variant="ghost"
                  onClick={() => publishOne(idx)}
                  loading={publishing === idx}
                >
                  Publish
                </Button>
              </div>
            </Card>
          ))}
        </div>
      )}

      {tasks.length === 0 && !generating && (
        <Card className="text-center py-12 text-white/50">
          Pick a profile and click Generate.
        </Card>
      )}
    </div>
  );
}
